package PECL;

import java.awt.Dimension;

public class ClienteRMI extends javax.swing.JFrame {
    private HiloRMI hilo;
    
    public ClienteRMI(){      
        initComponents();  
        this.setSize(new Dimension(1100,300));
        this.setLocationRelativeTo(null);
        this.setTitle(" MÓDULO DE VISUALIZACIÓN ");
        
        hilo = new HiloRMI(jTextField1MPedidos,jTextArea1PLlatos);
        hilo.start(); 
     }  
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texto1 = new javax.swing.JLabel();
        texto2 = new javax.swing.JLabel();
        jTextField1MPedidos = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1PLlatos = new javax.swing.JTextArea();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texto1.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        texto1.setText("Contenido del mostrador de pedidos:");
        getContentPane().add(texto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        texto2.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        texto2.setText("Contenido de la mesa de platos:");
        getContentPane().add(texto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jTextField1MPedidos.setEditable(false);
        jTextField1MPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1MPedidosActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1MPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 1020, 40));

        jTextArea1PLlatos.setEditable(false);
        jTextArea1PLlatos.setColumns(20);
        jTextArea1PLlatos.setRows(5);
        jScrollPane1.setViewportView(jTextArea1PLlatos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 166, 1030, 50));

        fondo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5284.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-220, -90, 1460, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1MPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1MPedidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1MPedidosActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteRMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteRMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteRMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteRMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteRMI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1PLlatos;
    private javax.swing.JTextField jTextField1MPedidos;
    private javax.swing.JLabel texto1;
    private javax.swing.JLabel texto2;
    // End of variables declaration//GEN-END:variables
}
