package PECL;

import java.awt.Dimension;
import java.rmi.Naming;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;


public class Restaurante extends javax.swing.JFrame {

    /**
     * Creates new form Restaurante
     */
    private MostradorPedidos mpedidos;
    private MesaPlatos mplatos;
    private Log log;
    private Pausar pararTodo;
    private Pausar pararEmpleado1;
    private Pausar pararEmpleado2;
    

    public Restaurante() {
        initComponents();
        this.setSize(new Dimension(1200,800));
        this.setLocationRelativeTo(null);
        this.setTitle(" RESTAURANTE ");
        
        //Mostrador aceptará máximo 10 pedidos y la mesa 20 pedidos
        mpedidos = new MostradorPedidos(10, MuestraTexto1);
        mplatos = new MesaPlatos(20, MuestraTexto4);
        log = new Log(); //Inicializamos el log
        log.crearArchivo();//Creamos el log 
        pararEmpleado1 = new Pausar(); //Inicializamos Pausar
        pararEmpleado2 = new Pausar();
        pararTodo = new Pausar();
       
        // Crearemos los hilos
        //200 Clientes  + su identificador + variable compartida Mostrador de Pedidos
        for (int i = 1; i <= 200;i++) {
            Cliente cli = new Cliente("Cliente" + i, mpedidos,log,pararTodo);
            cli.start(); 
        }
        //2 Empleados + variables compartidas Mesa de Platos y Mostrador de Pedidos
        Empleado emp1 = new Empleado("Empleado1", mpedidos, mplatos, MuestraTexto2,log, pararTodo, pararEmpleado1);
        Empleado emp2 = new Empleado("Empleado2", mpedidos, mplatos, MuestraTexto3,log, pararTodo, pararEmpleado2);
        
        //3 Cocineros + variable compartida Moesa de platos
        Cocinero co1 = new Cocinero("Cocinero1", mplatos, MuestraTexto5,log, pararTodo);
        Cocinero co2 = new Cocinero("Cocinero2", mplatos, MuestraTexto6,log, pararTodo);
        Cocinero co3 = new Cocinero("Cocinero3", mplatos, MuestraTexto7,log, pararTodo);
        //Lanzamos los hilos
        emp1.start();
        emp2.start();
        co1.start();
        co2.start();
        co3.start();
        
        //Servidor Remoto RMI
        try {
            //Crea instancia del objeto que implementa la interfaz (objeto a registrar):
            System.out.println("Servidor Arrancado....");
            ObjetoRMI obj = new ObjetoRMI(mplatos, mpedidos);
            Registry registry = LocateRegistry.createRegistry(1099); //Arranca rmiregistry local en el puerto 1099
            Naming.rebind("//127.0.0.1/ModuloV", obj); //Hace visible el objeto para clientes
            System.out.println("El Objeto ModuloV ha quedado registrado");

        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
            e.printStackTrace();
        }       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Texto2 = new javax.swing.JLabel();
        MuestraTexto1 = new javax.swing.JTextField();
        MuestraTexto2 = new javax.swing.JTextField();
        Texto3 = new javax.swing.JLabel();
        MuestraTexto3 = new javax.swing.JTextField();
        Texto4 = new javax.swing.JLabel();
        MuestraTexto4 = new javax.swing.JTextField();
        Texto5 = new javax.swing.JLabel();
        MuestraTexto5 = new javax.swing.JTextField();
        Texto6 = new javax.swing.JLabel();
        MuestraTexto6 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        MuestraTexto7 = new javax.swing.JTextField();
        BotonPausarTodo = new javax.swing.JButton();
        BotonReanudarTodo = new javax.swing.JButton();
        BotonPausarEmpleado1 = new javax.swing.JButton();
        BotonReanudarEmpleado1 = new javax.swing.JButton();
        Texto1 = new javax.swing.JLabel();
        BotonReanudarEmpleado2 = new javax.swing.JButton();
        BotonPausarEmpleado2 = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Texto2.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        Texto2.setText("Empleado 1:");
        getContentPane().add(Texto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        MuestraTexto1.setEditable(false);
        MuestraTexto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MuestraTexto1ActionPerformed(evt);
            }
        });
        getContentPane().add(MuestraTexto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 1030, 40));

        MuestraTexto2.setEditable(false);
        MuestraTexto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MuestraTexto2ActionPerformed(evt);
            }
        });
        getContentPane().add(MuestraTexto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 300, 40));

        Texto3.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        Texto3.setText("Empleado 2:");
        getContentPane().add(Texto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, -1, -1));

        MuestraTexto3.setEditable(false);
        MuestraTexto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MuestraTexto3ActionPerformed(evt);
            }
        });
        getContentPane().add(MuestraTexto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 340, 40));

        Texto4.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        Texto4.setText("Contenido de la mesa de platos:");
        getContentPane().add(Texto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        MuestraTexto4.setEditable(false);
        MuestraTexto4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MuestraTexto4ActionPerformed(evt);
            }
        });
        getContentPane().add(MuestraTexto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 1130, 42));

        Texto5.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        Texto5.setText("Cocinero 1:");
        getContentPane().add(Texto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, -1, -1));

        MuestraTexto5.setEditable(false);
        MuestraTexto5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MuestraTexto5ActionPerformed(evt);
            }
        });
        getContentPane().add(MuestraTexto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 340, 40));

        Texto6.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        Texto6.setText("Cocinero 2:");
        getContentPane().add(Texto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 480, -1, -1));

        MuestraTexto6.setEditable(false);
        getContentPane().add(MuestraTexto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 520, 340, 40));

        jLabel3.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        jLabel3.setText("Cocinero 3:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 480, -1, -1));

        MuestraTexto7.setEditable(false);
        MuestraTexto7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MuestraTexto7ActionPerformed(evt);
            }
        });
        getContentPane().add(MuestraTexto7, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 520, 300, 40));

        BotonPausarTodo.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        BotonPausarTodo.setText("Pausar Todo");
        BotonPausarTodo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonPausarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPausarTodoActionPerformed(evt);
            }
        });
        getContentPane().add(BotonPausarTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 610, -1, -1));

        BotonReanudarTodo.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        BotonReanudarTodo.setText("Reanudar Todo");
        BotonReanudarTodo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonReanudarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonReanudarTodoActionPerformed(evt);
            }
        });
        getContentPane().add(BotonReanudarTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 660, -1, -1));

        BotonPausarEmpleado1.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        BotonPausarEmpleado1.setText("Pausar Empleado 1");
        BotonPausarEmpleado1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonPausarEmpleado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPausarEmpleado1ActionPerformed(evt);
            }
        });
        getContentPane().add(BotonPausarEmpleado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 600, -1, -1));

        BotonReanudarEmpleado1.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        BotonReanudarEmpleado1.setText("Reanudar Empleado 1");
        BotonReanudarEmpleado1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonReanudarEmpleado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonReanudarEmpleado1ActionPerformed(evt);
            }
        });
        getContentPane().add(BotonReanudarEmpleado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 650, -1, -1));

        Texto1.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        Texto1.setText("Contenido del mostrador de pedidos:");
        getContentPane().add(Texto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        BotonReanudarEmpleado2.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        BotonReanudarEmpleado2.setText("Reanudar Empleado 2");
        BotonReanudarEmpleado2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonReanudarEmpleado2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonReanudarEmpleado2ActionPerformed(evt);
            }
        });
        getContentPane().add(BotonReanudarEmpleado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 650, -1, -1));

        BotonPausarEmpleado2.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        BotonPausarEmpleado2.setText("Pausar Empleado 2");
        BotonPausarEmpleado2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonPausarEmpleado2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPausarEmpleado2ActionPerformed(evt);
            }
        });
        getContentPane().add(BotonPausarEmpleado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 600, 160, 30));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/blue-and-white-marbleised-plain.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -10, 1260, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonReanudarEmpleado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonReanudarEmpleado2ActionPerformed
        // TODO add your handling code here:
        pararEmpleado2.seguir();
    }//GEN-LAST:event_BotonReanudarEmpleado2ActionPerformed

    private void BotonReanudarEmpleado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonReanudarEmpleado1ActionPerformed
        // TODO add your handling code here:
        pararEmpleado1.seguir();

    }//GEN-LAST:event_BotonReanudarEmpleado1ActionPerformed

    private void BotonReanudarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonReanudarTodoActionPerformed
        // TODO add your handling code here:
        pararTodo.seguir();
    }//GEN-LAST:event_BotonReanudarTodoActionPerformed

    private void BotonPausarEmpleado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPausarEmpleado2ActionPerformed
        // TODO add your handling code here:
        pararEmpleado2.parar();
    }//GEN-LAST:event_BotonPausarEmpleado2ActionPerformed

    private void BotonPausarEmpleado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPausarEmpleado1ActionPerformed
        // TODO add your handling code here:
        pararEmpleado1.parar();

    }//GEN-LAST:event_BotonPausarEmpleado1ActionPerformed

    private void BotonPausarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPausarTodoActionPerformed
        // TODO add your handling code here:
        pararTodo.parar();
    }//GEN-LAST:event_BotonPausarTodoActionPerformed

    private void MuestraTexto7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MuestraTexto7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MuestraTexto7ActionPerformed

    private void MuestraTexto5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MuestraTexto5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MuestraTexto5ActionPerformed

    private void MuestraTexto4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MuestraTexto4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MuestraTexto4ActionPerformed

    private void MuestraTexto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MuestraTexto3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MuestraTexto3ActionPerformed

    private void MuestraTexto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MuestraTexto2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MuestraTexto2ActionPerformed

    private void MuestraTexto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MuestraTexto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MuestraTexto1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restaurante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonPausarEmpleado1;
    private javax.swing.JButton BotonPausarEmpleado2;
    private javax.swing.JButton BotonPausarTodo;
    private javax.swing.JButton BotonReanudarEmpleado1;
    private javax.swing.JButton BotonReanudarEmpleado2;
    private javax.swing.JButton BotonReanudarTodo;
    private javax.swing.JTextField MuestraTexto1;
    private javax.swing.JTextField MuestraTexto2;
    private javax.swing.JTextField MuestraTexto3;
    private javax.swing.JTextField MuestraTexto4;
    private javax.swing.JTextField MuestraTexto5;
    private javax.swing.JTextField MuestraTexto6;
    private javax.swing.JTextField MuestraTexto7;
    private javax.swing.JLabel Texto1;
    private javax.swing.JLabel Texto2;
    private javax.swing.JLabel Texto3;
    private javax.swing.JLabel Texto4;
    private javax.swing.JLabel Texto5;
    private javax.swing.JLabel Texto6;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
